Repository Medici-Mansion/shinnyang-server, pull requests merged in 2023-12, with the labels that each got.

#3 [CHORE] 도커파일추가
  Dockerfile
Labels: ✅ 완료, 💻 [SERVER]

#17 Feat : global middleware 생성
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/common/interceptors/errors.interceptor.ts
  src/common/interceptors/undefiendToNull.interceptor.ts
  src/main.ts
  src/middlewares/logger.middleware.ts
Labels: 💻 [SERVER], 🔍 QA

#25 [CHORE] 배포를 위한 환경설정
  .dockerignore
  Dockerfile
  package.json
  pnpm-lock.yaml
  src/database/database.module.ts
Labels: 💻 [SERVER], 🔍 QA

#26 [SNP-39] 편지 / 답장 기능 구현
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/common/base.entity.ts
  src/common/interface.ts
  src/database/database.module.ts
  src/letters/dtos/create-letters.dto.ts
  src/letters/dtos/letters.dto.ts
  src/letters/entities/letter.entity.ts
  src/letters/letters.controller.ts
  src/letters/letters.module.ts
  src/letters/letters.repository.ts
  src/letters/letters.service.ts
  src/main.ts
  src/utils/response.utils.ts
Labels: 💻 [SERVER], 🔍 QA

#37 [SNP-74] 공통코드 제작
  src/app.module.ts
  src/common/common.controller.ts
  src/common/common.service.ts
  src/common/dto/cat.dto.ts
  src/common/entities/base.entity.ts
  src/common/entities/cats.entity.ts
  src/letters/dtos/create-letter.dto.ts
  src/letters/dtos/letter.dto.ts
Labels: 💻 [SERVER], 🔍 QA

#41 [SNP-70] Letter Entity ↔ Answer Entity 분리
  package-lock.json
  src/app.module.ts
  src/auth/auth.service.ts
  src/auth/dtos/jwt.dto.ts
  src/entities/letter.entity.ts
  src/letters/dtos/create-letter.dto.ts
  src/letters/dtos/letter.dto.ts
  src/letters/dtos/letter.request.dto.ts
  src/letters/dtos/letter.response.dto.ts
  src/letters/entities/letter.entity.ts
  src/letters/letter.controller.ts
  src/letters/letter.repository.ts
  src/letters/letter.service.ts
  src/users/dtos/create-users.dto.ts
  src/users/dtos/user.dto.ts
  src/users/user.repository.ts
  src/users/user.service.ts
Labels: 💻 [SERVER], 💡 수정요청

#46 [SNP-70] Letter Entity ↔ Answer Entity 분리
  src/answers/answer.controller.ts
  src/answers/answer.service.ts
  src/answers/dtos/answer.response.dto.ts
  src/app.module.ts
  src/entities/answer.entity.ts
  src/letters/dtos/letter.request.dto.ts
  src/letters/dtos/letter.response.dto.ts
  src/letters/letter.controller.ts
Labels: 💻 [SERVER], 💡 수정요청
